### ISSUE TITLE
All of plugins brokem after aliucord update

### ISSUE THREAD

**Issue by fym35** [lexisother/AliucordPlugins#6]
They just dont load with the message saying that there is no mainfest for them
![Screenshot_20211220_074820](https://user-images.githubusercontent.com/57803365/146723916-4e16eb42-331b-41c7-9086-39e4ca53cc8e.jpg)

**Comment by lexisother** [comment]
This isn't my plugin.

**Comment by lexisother** [comment]
To come back on this, I can safely say this is an Aliucord issue. All my plugins have a manifest. 

Try to reinstall the plugins, see if that fixes it. If not, complain to the Aliucord maintainers.

**Comment by fym35** [comment]
all other plugin devs have already updated their plugins to the new mainfest thats why none of your plugins and ltmgfy work -_-
