### ISSUE TITLE
HideBlockedMessages is broken on new update

### ISSUE THREAD

**Issue by fortnider** [lexisother/AliucordPlugins#8]
Title. Is supposed to hide blocked messages but does not. Has been broken for a few weeks.

**Comment by lexisother** [comment]
Thanks for reporting :)
I'll work on a fix in a few minutes

**Comment by lexisother** [comment]
Fixed in https://github.com/lexisother/AliucordPlugins/commit/4e7f56dc7a196a3a04c3dc5fee888308bccc8865!
